### ISSUE TITLE
Varialble are not loading in HA 73.1 && pyhomematic0.1.44

### ISSUE THREAD

**Issue by freeki** [danielperna84/pyhomematic#143]
There seems to be a problem in this mentioned combination.

Downgrading to previous version of HA (which includes downgrading pyhomematic) fixes the problem.

Is this a known issue?

With an unchanging configuration i get the following error message:

ServerThread.jsonRpcLogin: Exception while logging in via JSON-RPC: 'jsonport'

**Comment by danielperna84** [comment]
This break was not intended. The `jsonport` option marked as _optional_ in the [documentation](https://www.home-assistant.io/components/homematic/) seems to be mandatory after all. So version 73 should be working if you include `jsonport: 80` in your configuration. Can you verify my statement?

**Comment by freeki** [comment]
Actually not.

my config looks like this:

homematic:
  interfaces:
    rf1:
      host: 192.168.1.25
      jsonport: 80
      callback_ip: 192.168.1.45
      username: !secret CCU_username
      password: !secret CCU_password
  hosts:
    ccu2:
      host: 192.168.1.25
      username: !secret CCU_username
      password: !secret CCU_password


Still not working.
DEBUG message stays the same:
2018-07-10 11:01:38 DEBUG (SyncWorker_8) [pyhomematic._hm] ServerThread.jsonRpcLogin: Exception while logging in via JSON-RPC: 'jsonport'

**Comment by freeki** [comment]
I alread tried that before.
This does not work, too.

> [homematic]: [jsonport] is an invalid option for [homematic]. Check: homematic->homematic->hosts->ccu2->jsonport. (See /config/configuration.yaml, line 97). Please check the docs at https://home-assistant.io/components/homematic/

**Comment by danielperna84** [comment]
Ok, I see where the problem is. I'll have a deeper look at it this evening.

**Comment by e1nzelkind** [comment]
Same errors like freeki with the hosts and interfaces configuration. 

Thanks Daniel! :-)

**Comment by freeki** [comment]
Cool!
Thanks!

**Comment by danielperna84** [comment]
I have done a quick fix. It's in [_hm.py](https://github.com/danielperna84/pyhomematic/blob/fix_variables/pyhomematic/_hm.py). If you replace the whole file and restart HASS the variables should be working again. Can any of you guys confirm this?

**Comment by e1nzelkind** [comment]
Whoop whoop - variables are working again 👍 

Thank you very much for the fast fix Daniel! 🥇

**Comment by freeki** [comment]
Hmmm.. doesnt work for me.
whenever i restart HASS, the changes are gone.....

**Comment by freeki** [comment]
Never mind.
I committed the change to the container and now it is working.

Thanks for the quick fix Daniel!!!
Very much appreciated!

**Comment by danielperna84** [comment]
74 has been released. Closing this issue now.
