### ISSUE TITLE
HM-Wired support

### ISSUE THREAD

**Issue by torstenboe** [danielperna84/pyhomematic#38]
Like elajoie already asked for HM-IP, I wonder whether I can help in any way to add HM-wired devices to the supported device list? Changing from Port 2001 to Port 2000 the wired events are captured. Unfortunately I hadn't had the time to read out the data points, but I'll do that asap. 

16-09-23 18:32:20 INFO (Thread-2) [pyhomematic.devicetypes.generic] HMGeneric.event: address=MEQ0278841:15, interface_id=homeassistant, key=STATE, value=False
16-09-23 18:32:20 INFO (Thread-2) [pyhomematic.devicetypes.generic] HMGeneric.event: address=MEQ0278841:15, interface_id=homeassistant, key=WORKING, value=False
16-09-23 18:32:26 INFO (Thread-2) [pyhomematic.devicetypes.generic] HMGeneric.event: address=MEQ0278841:15, interface_id=homeassistant, key=STATE, value=True
16-09-23 18:32:26 INFO (Thread-2) [pyhomematic.devicetypes.generic] HMGeneric.event: address=MEQ0278841:15, interface_id=homeassistant, key=WORKING, value=False

**Comment by danielperna84** [comment]
I've created a small script to get the datapoints we need to implement the devices: [datapoints.py](https://github.com/danielperna84/pyhomematic/blob/master/datapoints.py)
Usage would be: ./datapoints.py http://1.2.3.4:2000 devices.json
Or leave out the filename if you want to have a look at the data first.

But yes, in general it should be no problem to also support wired devices.

**Comment by danielperna84** [comment]
I have now (hopefully correctly, can't test it) implemented all wired devices except the HMW-IO-12-Sw14-DR, which seems to be a bit more tricky because of all the different functionality it provides. For this only the 6 on/off switches are implemented.
Please wait for updated HA-code that makes use of the new devices and the changes made in pyhomematic to support them. The current code is not compatible with HA.

**Comment by danielperna84** [comment]
By the way, you can try to toggle switches using the [test.py](https://github.com/danielperna84/pyhomematic/blob/master/test.py) script. Clone the repository, and from there do something like:
```
python3 test.py -l LOCAL_IP -r REMOTE_IP -rp 2000 -a MEQ0278841 -c 15
python3 test.py -l LOCAL_IP -r REMOTE_IP -rp 2000 -a MEQ0278841 -c 15 -s True # or False to switch off
```

**Comment by danielperna84** [comment]
Any feedback on this @torstenboe ?

**Comment by danielperna84** [comment]
@torstenboe 
Would it be possible for you to checkout the branch [this](https://github.com/danielperna84/pyhomematic/pull/42) pull request is about and report if you can get the regular devices and IP devices running in parallel?
From the python shell it would be done something like this:
```python
import logging
from pyhomematic import HMConnection

logging.basicConfig(level=logging.DEBUG)

def systemcallback(src, *args):
    print(src)
    for arg in args:
        print(arg)

pyhomematic = HMConnection(interface_id="myserver",
                           local="192.168.0.2",
                           localport=7080,
                           remotes={'hmrf': {'ip': '192.168.0.4', 'port': 2001}, 'hmw': {'ip': '192.168.0.4', 'port': 2000}}
                           autostart=True,
                           systemcallback=systemcallback)
print(pyhomematic.devices)
```

**Comment by torstenboe** [comment]
Hi Daniel, sorry, I was upset for a while. Get back to my PC and try it next week.

**Comment by danielperna84** [comment]
The PR mentioned above has been mergen meanwhile. But still it would make sense to see if this solution enables you to use wired and wireless devices in paralel.

**Comment by danielperna84** [comment]
Meanwhile Home Assistant 0.34 has been released, which includes support for HomeMatic wired. Can you confirm it is working?

**Comment by torstenboe** [comment]
Let me try, I'll come back

**Comment by FREImedia** [comment]
Hi, I've just setup homematic wired components and tried to add them to home assistant.

He're the things i noticed / the problems I have:
I have two HMW-IO-12-Sw14-DR. Neither the inputs nor the outputs are displayed on the HA states pages.
With the setvalue service I can easily turn on or off the outputs from HA. So thats working well.
The problem I have is that I can't use the homematic wired inputs to trigger HA events.
I can see a pyhomeatic log output, that there was an event, but it seems like its not passed over or processed by HA.

`16-12-11 22:51:21 pyhomematic.devicetypes.generic: HMGeneric.event: address=NEQXXXXX:16, interface_id=homeassistant-wired, key=STATE, value=True
`

Is there any way to listen on these type of events with HA?

Another thing I have tried and noticed, that if a CCU2 system variable changes its state, there is no event on HA. 

Thanks for your support :-)

**Comment by danielperna84** [comment]
Hi,

the HMW-IO-12-Sw14-DR is currently not supported. Compared to the other wired devices it's quite complex, and the specifications aren't clear enough to ensure a proper implementation without knowing anything about the device. But with your help we could get it to work.

The documentation describes the device as follows:

| Kanaltyp | Kanalnummer | Parameter | Typ |
| :--- | :--- | :--- | :--- |
| DIGITAL_OUTPUT | 1 bis 6 | STATE | bool |
| DIGITAL_ANALOG_OUTPUT | 7 bis 14 | FREQUENCY | float |
| DIGITAL_INPUT | 15 bis 20 | FREQUENCY | float |
| DIGITAL_ANALOG_INPUT | 21 bis 26 | VALUE | float |

Which channels did you use to manually set states and can  confirm they are working? Just 1 - 6 or also 7 - 14?
What's irritating me is the log you've posted. Compared to the table above channel 16 should be a float-value, but it's logged as bool. Does that make sense? The name DIGITAL_INPUT actually sounds more like it should be a bool-value, so maybe the documentation has an error in that case.
And I guess the input-channels should be imlemented as sensors in HASS.

This implementation has to be done for you to be able to react on those events. There is no way to capture these kind of events manually.

And yes, there is no event when a variable changes with the CCU2. That's why we have to poll every 30s to see if a variable has changed. Homegear sends events those events, but to be fully compatible we've chosen to rely on the polling-method for now. So if you don't see a variable change in HASS, whait 30s.

**Comment by FREImedia** [comment]
Thanks for your quick reply!
At the moment my setup is still very small.
I have connected four wall switches as digital inputs (channel 15, 16, 17, 18) and two lamps with relais on the relais-output ports (1 and 2).

As far as I understood the CCU2 webui, digital inputs only  have bool variables. The CCU2 shows only a bool state for channel 15 ("on" and "off") for example.

I have attached you some screenshots from the ccu2, maybe they help you!

In HASS I cant see the input channels as sensors on the states page - is this already implemented?

Best, 
Matthias
<img width="1065" alt="bildschirmfoto 2016-12-12 um 00 41 04" src="https://cloud.githubusercontent.com/assets/12660103/21084453/36827d22-c004-11e6-9ddc-7ce2b7f3a860.png">
<img width="1055" alt="bildschirmfoto 2016-12-12 um 00 40 50" src="https://cloud.githubusercontent.com/assets/12660103/21084455/36b65264-c004-11e6-991b-7193e18c051e.png">
<img width="1440" alt="bildschirmfoto 2016-12-12 um 00 40 18" src="https://cloud.githubusercontent.com/assets/12660103/21084454/36b04cde-c004-11e6-94d4-3b3ddde8b404.png">

**Comment by danielperna84** [comment]
The device isn't at all implemented in pyhomematic. Therefore HASS doesen't know anything about the device. No switches, no sensors. Every aspect of the device has to be implemented in pyhomematic before we create entites in HASS. The fact that you can control the device with the the service in HASS has no relation to implemented support. That's exactly why we have added the service: so people with devices that are not supported at least can control their devices manually.

Looking at the screenshots it gets clear, that the channels 7 - 14 can be either analog (which would be float) and digital (which would be bool). Do you have anything attached to one of those channels? If so it would be intersting to see, if setting a value of `0.0` is equivalent to `false` and everything above that would be considered `true`.
In general the channels 1 - 6 are no problem. The ones following though seem to be tricky if they all can operate in ether a digital or analog mode. We would need some way to detect the operational mode, but there's nothing in the documentation about that.

**Comment by danielperna84** [comment]
Here's what ELV has to say about the device:

> Die Eingänge sind standardmäßig als digitale Eingänge, 6 als TTL-Eingang bzw. Kontakt mit Pull-Up-Widerstand, 6 als digitale 0/10V Eingänge ausgeführt. Die Eingänge lassen sich nicht für Direktverknüpfungen nutzen. In Programmen kann der Zustand der Eingänge verarbeitet werden. Die eine Hälfte der digitalen Eingänge lässt sich auch zur Frequenzmessung nutzen, die andere Hälfte kann alternativ für Spannungsmessungen verwendet werden. Die OpenCollector Schaltausgänge können auch als Frequenz- bzw. PWM-Ausgänge genutzt werden. Alle Ausgänge lassen sich jedoch nur über Programme steuern und nicht in Direktverknüpfungen verwenden.

> Die Ansteuerung von Türöffnern und anderen Kleinspannungs-Aktoren, die Erfassung von Schaltkontakten und/oder Sensordaten sind nur einige der vielen möglichen Einsatzbereiche des Moduls, das bequem via Homematic Zentrale und PC programmiert werden kann.

> 6 digitale Eingänge, TTL-kompatibel, auch mit Schaltern/Tastern gegen Masse schaltbar
6 analoge Eingänge: Eingangsspannung bis 10 V, z. B. für Sensoren, Analogwertgeber usw.
8 Open-Collector-Schaltausgänge, bis 24 V/50 mA, z. B. für Relais oder LEDs
6 Relais-Schaltausgänge, bis 24 V/0,8 A, Arbeitskontakt
Hinweis: Mit den Eingängen sind keine Direktverknüpfungen zu Aktoren möglich, stattdessen können zustandsabhängig in Programmen Aktionen ausgelöst werden.

I'm not sure how and if all the upper channels can be implemented in HASS.

**Comment by FREImedia** [comment]
I have tested the following:

I have no device connected to port 7, but I can see the port state in the CCU2 webui:

{"address": "NEQXXX", "channel": "7", "param": "VALUE", "value": "1"}
does not change the port state

{"address": "NEQXXX", "channel": "7", "param": "STATE", "value": "1"}
sets the port state to ON

{"address": "NEQXXX", "channel": "7", "param": "VALUE", "value": "0"}
does not change the port state

{"address": "NEQXXX", "channel": "7", "param": "STATE", "value": "0"}
sets the port state to OFF

{"address": "NEQXXX", "channel": "7", "param": "STATE", "value": "2.5"}
sets the port state to ON

In my case I only work with digital inputs and outputs, as I need this device primarily to control lamps and get the state of switches.
Actually I would really need to react on those events described in my first post. Do you think its possible to implement the "basic" functionality for this device so you can read and set digital states and get events in HASS?

**Comment by danielperna84** [comment]
I assume you have set the port to digital mode. What happens when you switch to analog mode and do exactly the same as above? Do you have to use the `FREQUENCY` parameter instead of `STATE` to control the port?

**Comment by FREImedia** [comment]
Exactly, digital - as shown in the screenshot.
If I set port 7 to analog, the following commands are NOT working:
{"address": "NEQXXX", "channel": "7", "param": "VALUE", "value": "1"}
{"address": "NEQXXX", "channel": "7", "param": "STATE", "value": "1"}
{"address": "NEQXXX", "channel": "7", "param": "VALUE", "value": "0"}
{"address": "NEQXXX", "channel": "7", "param": "STATE", "value": "0"}
{"address": "NEQXXX", "channel": "7", "param": "STATE", "value": "2.5"}

I changed param to FREQUENCY and it works.
{"address": "NEQXXX", "channel": "7", "param": "FREQUENCY", "value": "1"}
-> 1 MHz
{"address": "NEQXXX", "channel": "7", "param": "FREQUENCY", "value": "0"}
-> 0 MHz
{"address": "NEQXXX", "channel": "7", "param": "FREQUENCY", "value": "2.5"}
-> 3 MHz

**Comment by danielperna84** [comment]
In that case we would need some way to detect which mode is being used. Otherwise we would not know what kind of HASS-entity would be the correct one to match the channel.

Could you extract the datapoints manually using [this](https://github.com/danielperna84/pyhomematic/blob/master/datapoints.py) script? Just run, save as json and post as a gist? The hardware addresses are being anonymized, so need to worry about that. And maybe there's some not documented parameter that tells us the operational mode.

**Comment by FREImedia** [comment]
https://gist.github.com/FREImedia/e43df6ee2ddd7726d3eb1b632139e32d

here is the result :-)

**Comment by danielperna84** [comment]
You seem to have used port 2001 since I'm seeing wireless devices. For wired devices you have to use port 2000.

**Comment by FREImedia** [comment]
True story. I just scrolled through the results again and wondered why i cannot find the wired devices..... (bed time 👍 )

https://gist.github.com/FREImedia/9f2bd19a91df3ec5e0666f0f7e0c138d

**Comment by danielperna84** [comment]
Hhmm, this really will be tricky to implement. At least for HASS, since I don't think there's an entity type that can include everything this IO module is capable of.
By looking at the description I assume channels 7 - 14 can be used as follows (directly in a Python 3 shell):

```python
from xmlrpc.client import ServerProxy

# Create the proxy object used to communicate with CCU
p = ServerProxy("http://1.2.3.4:2000")

# Display operational mode (0 -> Analog, 1 -> Digital)
p.getParamset("NEQXXX:7", "MASTER", "BEHAVIOUR")
# Set mode to digital
p.putParamset("NEQXXX:7", "MASTER", "BEHAVIOUR", 1)

# Turn on while in digital mode (this also is how channels 1 - 7 work)
p.setValue("NEQXXX:7", "STATE", True)
# Turn off again
p.setValue("NEQXXX:7", "STATE", False)
# Current state, shoule be False
p.getValue("NEQXXX:7", "STATE")

# Set mode to analog
p.putParamset("NEQXXX:7", "MASTER", "BEHAVIOUR", 0)
# Set frequency to 500MHz. Does 500 instead of 500.0 do anything different? The 2.5 from your test results in 3MHz
p.setValue("NEQXXX:7", "FREQUENCY", 500.0)
# Verify the value, should be 500.0 (or just 500 as an integer?)
p.getValue("NEQXXX:7", "FREQUENCY")
# There's also a pulsetime parameter, 0 by default
p.getParamset("NEQXXX:7", "MASTER", "PULSETIME")
# Set to 2, but could fail if frequency if >0 / device is in ON-state
p.putParamset("NEQXXX:7", "MASTER", "PULSETIME", 2.0)
# Turn off again
p.setValue("NEQXXX:7", "FREQUENCY", 0.0)
# Verify the value, should be 0.0 (or just 0 as an integer?)
p.getValue("NEQXXX:7", "FREQUENCY")
```

Can you confirm this?

**Comment by FREImedia** [comment]
I opened a python3 shell and entered the commands. Here is the result:

`>>> p.getParamset("NEQXXX:7", "MASTER", "BEHAVIOUR")
{'PULSETIME': 0.0, 'BEHAVIOUR': 0}
>>> p.putParamset("NEQXXX:7", "MASTER", "BEHAVIOUR", 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1089, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1131, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1147, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1318, in parse_response
    return u.close()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'type error'>
>>> p.setValue("NEQXXX:7", "STATE", True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1089, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1131, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1147, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1318, in parse_response
    return u.close()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'Failure'>
>>> p.setValue("NEQXXX:7", "STATE", False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1089, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1131, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1147, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1318, in parse_response
    return u.close()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'Failure'>
>>> p.getValue("NEQXXX:7", "STATE")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1089, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1131, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1147, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1318, in parse_response
    return u.close()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'Failure'>
>>> 
>>> p.putParamset("NEQXXX:7", "MASTER", "BEHAVIOUR", 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1089, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1131, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1147, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1318, in parse_response
    return u.close()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'type error'>
>>> p.setValue("NEQXXX:7", "FREQUENCY", 500.0)
''
>>> p.getValue("NEQXXX:7", "FREQUENCY")
500.0
>>> p.getParamset("NEQXXX:7", "MASTER", "PULSETIME")
{'PULSETIME': 0.0, 'BEHAVIOUR': 0}
>>> p.putParamset("NEQXXX:7", "MASTER", "PULSETIME", 2.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1089, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1419, in __request
    verbose=self.__verbose
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1131, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1147, in single_request
    return self.parse_response(resp)
  File "/usr/lib/python3.4/xmlrpc/client.py", line 1318, in parse_response
    return u.close()
  File "/usr/lib/python3.4/xmlrpc/client.py", line 656, in close
    raise Fault(**self._stack[0])
xmlrpc.client.Fault: <Fault -1: 'type error'>
>>> p.setValue("NEQXXX:7", "FREQUENCY", 0.0)
''
>>> p.getValue("NEQXXX:7", "FREQUENCY")
0.0`

**Comment by danielperna84** [comment]
I just realized I've used the wrong syntax for the putParamset-method. Here's an example of how it should look like:
```python
# do
p.putParamset("NEQXXX:7", "MASTER", {"BEHAVIOUR": 0})
# instead of
p.putParamset("NEQXXX:7", "MASTER", "BEHAVIOUR", 0)
```
putParamset expects a dictionary. Forgot about that. If that way you succeed changing the mode, you shouldn't get any exceptions anymore.

**Comment by FREImedia** [comment]
Yep, now it works :-)
See the result attached!
[result.txt](https://github.com/danielperna84/pyhomematic/files/650348/result.txt)

**Comment by FREImedia** [comment]
Do you need any further assistance or have you got all the information you need for implementation? :-)

**Comment by danielperna84** [comment]
I think that's all we need. Just a matter of time now.

**Comment by danielperna84** [comment]
@FREImedia 
HMW-IO-12-Sw14-DR should be working now with HASS 0.36.0. Could you please verify this?

**Comment by FREImedia** [comment]
Hey @danielperna84,

its not working yet. :-(
The error message on startup:
`17-01-16 09:10:47 INFO (Thread-3) [pyhomematic._hm] Proxy initialized
17-01-16 09:10:47 CRITICAL (Thread-13) [pyhomematic._hm] RPCFunctions.createDeviceObjects: Parent: 'HMWIOSwitch' object has no attribute '_doc'
17-01-16 09:10:48 CRITICAL (Thread-13) [pyhomematic._hm] RPCFunctions.createDeviceObjects: Parent: 'HMWIOSwitch' object has no attribute '_doc'
17-01-16 09:10:48 CRITICAL (Thread-13) [pyhomematic._hm] RPCFunctions.createDeviceObjects: Child: 'NEQXXX'
17-01-16 09:10:48 CRITICAL (Thread-13) [pyhomematic._hm] RPCFunctions.createDeviceObjects: Child: 'NEQXXX'
17-01-16 09:10:48 CRITICAL (Thread-13) [pyhomematic._hm] RPCFunctions.createDeviceObjects: Child: 'NEQXXX'
17-01-16 09:10:48 CRITICAL (Thread-13) [pyhomematic._hm] RPCFunctions.createDeviceObjects: Child: 'NEQXXX'
17-01-16 09:10:48 CRITICAL (Thread-13) [pyhomematic._hm] RPCFunctions.createDeviceObjects: Child: 'NEQXXX'
17-01-16 09:10:48 CRITICAL (Thread-13) [pyhomematic._hm] RPCFunctions.createDeviceObjects: Child: 'NEQXXX'
...
`

**Comment by danielperna84** [comment]
Hhmm... I wonder why it doesn't see the _doc-attribute. @pvizeli any idea?

**Comment by FREImedia** [comment]
Theres another problem since this update:
Its not possible to use 'homematic.set_dev_value' on the HMWiredIO devices anymore. 
17-01-16 22:13:16 ERROR (Thread-4) [homeassistant.components.homematic] NEQXXX not found!

Can this could be caused by your change? I haven't changed my configuration with this update (and now I cannot turn on or off my devices anymore :-( )
I already tried to restart HA and CCU2.

Thanks for your assistance and your work!

**Comment by danielperna84** [comment]
Yes, not being able to use set_value is caused by the changes that came with the new pyhomematic release. Before the changes, you got generic devices which supported the set_value commands. Now creating the objects fails completly, so there's nowhere you can point set_value at.

Meanwhile I've created another branch with a lot of logging to see how far we get when creating the parent object: [HMWIO_fix](https://github.com/danielperna84/pyhomematic/tree/HMWIO_fix)

Could you please clone this branch and test it manually? Not with HASS, but directly. For that, enter the following code (replace 127.0.0.1 with the IP of your CCU) into an interactive Python 3 shell:

```python
import logging
from pyhomematic import HMConnection
logging.basicConfig(level=logging.DEBUG)

p = HMConnection(interface_id="myserver", autostart=True, remotes={"wired":{"ip":"127.0.0.1","port": 2000}})
```

This will print out a lot of data. The lines I am looking for are those starting with "HMWIOSwitch".
Before you quit the interpreter, you have to close the connection with `p.stop()`.

And as a workaround to get back control of your device you can comment out line 373 ("HMW-IO-12-Sw14-DR": HMWIOSwitch,) in actors.py, which tells pyhomematic to use the HMIOSwitch-class instead of the generic one.

**Comment by FREImedia** [comment]
Thanks again for your quick reply. The workaround worked! Cheers! 

Here is the part of the debug log you requested:

> DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: iterating interface_id = wired
> DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: BidCoS-Wir : {'FIRMWARE': '2.25.15', 'CHILDREN': ['BidCoS-Wir:0', 'BidCoS-Wir:1', 'BidCoS-Wir:2', 'BidCoS-Wir:3', 'BidCoS-Wir:4', 'BidCoS-Wir:5', 'BidCoS-Wir:6', 'BidCoS-Wir:7', 'BidCoS-Wir:8', 'BidCoS-Wir:9', 'BidCoS-Wir:10', 'BidCoS-Wir:11', 'BidCoS-Wir:12', 'BidCoS-Wir:13', 'BidCoS-Wir:14', 'BidCoS-Wir:15', 'BidCoS-Wir:16', 'BidCoS-Wir:17', 'BidCoS-Wir:18', 'BidCoS-Wir:19', 'BidCoS-Wir:20', 'BidCoS-Wir:21', 'BidCoS-Wir:22', 'BidCoS-Wir:23', 'BidCoS-Wir:24', 'BidCoS-Wir:25', 'BidCoS-Wir:26', 'BidCoS-Wir:27', 'BidCoS-Wir:28', 'BidCoS-Wir:29', 'BidCoS-Wir:30', 'BidCoS-Wir:31', 'BidCoS-Wir:32', 'BidCoS-Wir:33', 'BidCoS-Wir:34', 'BidCoS-Wir:35', 'BidCoS-Wir:36', 'BidCoS-Wir:37', 'BidCoS-Wir:38', 'BidCoS-Wir:39', 'BidCoS-Wir:40', 'BidCoS-Wir:41', 'BidCoS-Wir:42', 'BidCoS-Wir:43', 'BidCoS-Wir:44', 'BidCoS-Wir:45', 'BidCoS-Wir:46', 'BidCoS-Wir:47', 'BidCoS-Wir:48', 'BidCoS-Wir:49', 'BidCoS-Wir:50'], 'PARENT': '', 'ADDRESS': 'BidCoS-Wir', 'TYPE': 'HMW-RCV-50', 'VERSION': 3, 'FLAGS': 9, 'PARAMSETS': ['MASTER'], 'UPDATABLE': 1}
> DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: created BidCoS-Wir  as SUPPORTED device for HMW-RCV-50
> DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices_all
> DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices
> DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: __init__
> DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: NEQXXX01 : {'FIRMWARE': '1.00', 'CHILDREN': ['NEQXXX01:0', 'NEQXXX01:1', 'NEQXXX01:2', 'NEQXXX01:3', 'NEQXXX01:4', 'NEQXXX01:5', 'NEQXXX01:6', 'NEQXXX01:7', 'NEQXXX01:8', 'NEQXXX01:9', 'NEQXXX01:10', 'NEQXXX01:11', 'NEQXXX01:12', 'NEQXXX01:13', 'NEQXXX01:14', 'NEQXXX01:15', 'NEQXXX01:16', 'NEQXXX01:17', 'NEQXXX01:18', 'NEQXXX01:19', 'NEQXXX01:20', 'NEQXXX01:21', 'NEQXXX01:22', 'NEQXXX01:23', 'NEQXXX01:24', 'NEQXXX01:25', 'NEQXXX01:26'], 'PARENT': '', 'ADDRESS': 'NEQXXX01', 'AVAILABLE_FIRMWARE': '1.00', 'TYPE': 'HMW-IO-12-Sw14-DR', 'VERSION': 12, 'FLAGS': 1, 'PARAMSETS': ['MASTER'], 'UPDATABLE': 1}
> DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch.ELEMENT: Returning self._doc
> CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Parent: 'HMWIOSwitch' object has no attribute '_doc'
> DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: __init__
> DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: NEQXXX02 : {'FIRMWARE': '1.00', 'CHILDREN': ['NEQXXX02:0', 'NEQXXX02:1', 'NEQXXX02:2', 'NEQXXX02:3', 'NEQXXX02:4', 'NEQXXX02:5', 'NEQXXX02:6', 'NEQXXX02:7', 'NEQXXX02:8', 'NEQXXX02:9', 'NEQXXX02:10', 'NEQXXX02:11', 'NEQXXX02:12', 'NEQXXX02:13', 'NEQXXX02:14', 'NEQXXX02:15', 'NEQXXX02:16', 'NEQXXX02:17', 'NEQXXX02:18', 'NEQXXX02:19', 'NEQXXX02:20', 'NEQXXX02:21', 'NEQXXX02:22', 'NEQXXX02:23', 'NEQXXX02:24', 'NEQXXX02:25', 'NEQXXX02:26'], 'PARENT': '', 'ADDRESS': 'NEQXXX02', 'AVAILABLE_FIRMWARE': '1.00', 'TYPE': 'HMW-IO-12-Sw14-DR', 'VERSION': 12, 'FLAGS': 1, 'PARAMSETS': ['MASTER'], 'UPDATABLE': 1}
> DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch.ELEMENT: Returning self._doc
> CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Parent: 'HMWIOSwitch' object has no attribute '_doc'
> DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: BidCoS-Wir:0 : {'TYPE': 'MAINTENANCE', 'VERSION': 3, 'PARENT_TYPE': 'HMW-RCV-50', 'INDEX': 0, 'PARAMSETS': ['MASTER', 'VALUES'], 'AES_ACTIVE': 0, 'DIRECTION': 0, 'PARENT': 'BidCoS-Wir', 'ADDRESS': 'BidCoS-Wir:0', 'LINK_SOURCE_ROLES': '', 'LINK_TARGET_ROLES': '', 'FLAGS': 3}
>

**Comment by danielperna84** [comment]
Glad the workaround fixed it.

I've pushed another commit to the fix-branch. Could you pull again? I've actually just changed the order of some statements to if we get further this way.

**Comment by FREImedia** [comment]
```
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: iterating interface_id = wired
DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: BidCoS-Wir : {'FLAGS': 9, 'PARENT': '', 'UPDATABLE': 1, 'PARAMSETS': ['MASTER'], 'TYPE': 'HMW-RCV-50', 'CHILDREN': ['BidCoS-Wir:0', 'BidCoS-Wir:1', 'BidCoS-Wir:2', 'BidCoS-Wir:3', 'BidCoS-Wir:4', 'BidCoS-Wir:5', 'BidCoS-Wir:6', 'BidCoS-Wir:7', 'BidCoS-Wir:8', 'BidCoS-Wir:9', 'BidCoS-Wir:10', 'BidCoS-Wir:11', 'BidCoS-Wir:12', 'BidCoS-Wir:13', 'BidCoS-Wir:14', 'BidCoS-Wir:15', 'BidCoS-Wir:16', 'BidCoS-Wir:17', 'BidCoS-Wir:18', 'BidCoS-Wir:19', 'BidCoS-Wir:20', 'BidCoS-Wir:21', 'BidCoS-Wir:22', 'BidCoS-Wir:23', 'BidCoS-Wir:24', 'BidCoS-Wir:25', 'BidCoS-Wir:26', 'BidCoS-Wir:27', 'BidCoS-Wir:28', 'BidCoS-Wir:29', 'BidCoS-Wir:30', 'BidCoS-Wir:31', 'BidCoS-Wir:32', 'BidCoS-Wir:33', 'BidCoS-Wir:34', 'BidCoS-Wir:35', 'BidCoS-Wir:36', 'BidCoS-Wir:37', 'BidCoS-Wir:38', 'BidCoS-Wir:39', 'BidCoS-Wir:40', 'BidCoS-Wir:41', 'BidCoS-Wir:42', 'BidCoS-Wir:43', 'BidCoS-Wir:44', 'BidCoS-Wir:45', 'BidCoS-Wir:46', 'BidCoS-Wir:47', 'BidCoS-Wir:48', 'BidCoS-Wir:49', 'BidCoS-Wir:50'], 'FIRMWARE': '2.25.15', 'ADDRESS': 'BidCoS-Wir', 'VERSION': 3}
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: created BidCoS-Wir  as SUPPORTED device for HMW-RCV-50
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices_all
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: __init__
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: super()
DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: NEQXXX01 : {'FLAGS': 1, 'PARENT': '', 'UPDATABLE': 1, 'PARAMSETS': ['MASTER'], 'AVAILABLE_FIRMWARE': '1.00', 'CHILDREN': ['NEQXXX01:0', 'NEQXXX01:1', 'NEQXXX01:2', 'NEQXXX01:3', 'NEQXXX01:4', 'NEQXXX01:5', 'NEQXXX01:6', 'NEQXXX01:7', 'NEQXXX01:8', 'NEQXXX01:9', 'NEQXXX01:10', 'NEQXXX01:11', 'NEQXXX01:12', 'NEQXXX01:13', 'NEQXXX01:14', 'NEQXXX01:15', 'NEQXXX01:16', 'NEQXXX01:17', 'NEQXXX01:18', 'NEQXXX01:19', 'NEQXXX01:20', 'NEQXXX01:21', 'NEQXXX01:22', 'NEQXXX01:23', 'NEQXXX01:24', 'NEQXXX01:25', 'NEQXXX01:26'], 'TYPE': 'HMW-IO-12-Sw14-DR', 'FIRMWARE': '1.00', 'ADDRESS': 'NEQXXX01', 'VERSION': 12}
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch.ELEMENT: Returning self._doc
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: super() done
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Checking channels in self._daoc
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Setting defaults for inputs
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Checking channels in self._dfic
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Checking channels in self._daic
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Initializing metadata
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Parent: update expected at most 1 arguments, got 2
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: __init__
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: super()
DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: NEQXXX02 : {'FLAGS': 1, 'PARENT': '', 'UPDATABLE': 1, 'PARAMSETS': ['MASTER'], 'AVAILABLE_FIRMWARE': '1.00', 'CHILDREN': ['NEQXXX02:0', 'NEQXXX02:1', 'NEQXXX02:2', 'NEQXXX02:3', 'NEQXXX02:4', 'NEQXXX02:5', 'NEQXXX02:6', 'NEQXXX02:7', 'NEQXXX02:8', 'NEQXXX02:9', 'NEQXXX02:10', 'NEQXXX02:11', 'NEQXXX02:12', 'NEQXXX02:13', 'NEQXXX02:14', 'NEQXXX02:15', 'NEQXXX02:16', 'NEQXXX02:17', 'NEQXXX02:18', 'NEQXXX02:19', 'NEQXXX02:20', 'NEQXXX02:21', 'NEQXXX02:22', 'NEQXXX02:23', 'NEQXXX02:24', 'NEQXXX02:25', 'NEQXXX02:26'], 'TYPE': 'HMW-IO-12-Sw14-DR', 'FIRMWARE': '1.00', 'ADDRESS': 'NEQXXX02', 'VERSION': 12}
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch.ELEMENT: Returning self._doc
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: super() done
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Checking channels in self._daoc
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog output
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Setting defaults for inputs
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Checking channels in self._dfic
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found frequency input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Checking channels in self._daic
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Found analog input
DEBUG:pyhomematic.devicetypes.actors:HMWIOSwitch: Initializing metadata
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Parent: update expected at most 1 arguments, got 2
DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: BidCoS-Wir:0 : {'FLAGS': 3, 'PARENT': 'BidCoS-Wir', 'LINK_SOURCE_ROLES': '', 'PARAMSETS': ['MASTER', 'VALUES'], 'DIRECTION': 0, 'ADDRESS': 'BidCoS-Wir:0', 'VERSION': 3, 'PARENT_TYPE': 'HMW-RCV-50', 'TYPE': 'MAINTENANCE', 'INDEX': 0, 'LINK_TARGET_ROLES': '', 'AES_ACTIVE': 0}
...

DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: BidCoS-Wir:50 : {'FLAGS': 1, 'PARENT': 'BidCoS-Wir', 'LINK_SOURCE_ROLES': 'SWITCH', 'PARAMSETS': ['LINK', 'MASTER', 'VALUES'], 'DIRECTION': 1, 'ADDRESS': 'BidCoS-Wir:50', 'VERSION': 3, 'PARENT_TYPE': 'HMW-RCV-50', 'TYPE': 'VIRTUAL_KEY', 'INDEX': 50, 'LINK_TARGET_ROLES': '', 'AES_ACTIVE': 0}
DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: NEQXXX01:0 : {'FLAGS': 3, 'PARENT': 'NEQXXX01', 'LINK_SOURCE_ROLES': '', 'PARAMSETS': ['MASTER', 'VALUES'], 'DIRECTION': 0, 'ADDRESS': 'NEQXXX01:0', 'VERSION': 12, 'PARENT_TYPE': 'HMW-IO-12-Sw14-DR', 'TYPE': 'MAINTENANCE', 'INDEX': 0, 'LINK_TARGET_ROLES': '', 'AES_ACTIVE': 0}
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: 'NEQXXX01'
DEBUG:pyhomematic.devicetypes.generic:HMGeneric.__init__: device_description: NEQXXX01:1 : {'FLAGS': 1, 'PARENT': 'NEQXXX01', 'LINK_SOURCE_ROLES': '', 'PARAMSETS': ['MASTER', 'VALUES'], 'DIRECTION': 0, 'ADDRESS': 'NEQXXX01:1', 'VERSION': 12, 'PARENT_TYPE': 'HMW-IO-12-Sw14-DR', 'TYPE': 'DIGITAL_OUTPUT', 'INDEX': 1, 'LINK_TARGET_ROLES': '', 'AES_ACTIVE': 0}
CRITICAL:pyhomematic._hm:RPCFunctions.createDeviceObjects: Child: 'NEQXXX01'
...
```

**Comment by danielperna84** [comment]
Added another commit. Removed the logs and added a fix. If I'm correct, it should be working now and no CRITICAL messages should appear.

**Comment by FREImedia** [comment]
you are correct!

tadaaaa:
```
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: created BidCoS-Wir  as SUPPORTED device for HMW-RCV-50
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices_all
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices
...
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: created NEQXXX01  as SUPPORTED device for HMW-IO-12-Sw14-DR
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices_all
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices
...
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: created NEQXXX02  as SUPPORTED device for HMW-IO-12-Sw14-DR
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices_all
DEBUG:pyhomematic._hm:RPCFunctions.createDeviceObjects: adding to self.devices
...
```

**Comment by danielperna84** [comment]
Great! :)

Next test: replace the actors.py HASS is using with the one from this branch. You shoul now have all the switches PLUS sensor-entites for the input channels.

**Comment by FREImedia** [comment]
Yes, sir!
But its still not solved ;-)
[hass_log.txt](https://github.com/danielperna84/pyhomematic/files/709582/hass_log.txt)

I tried to manually call the "switch.turn_on" service on the new discovered switches (current state "unavailable"), but it did not change the devices state... As a note, some sensors do have the suffix "_frequency". On the CCU2 platform all devices are set to digital mode.

**Comment by danielperna84** [comment]
Does the set_dev_value service work again with this code?
I'm not sure why the switches don't work though. The RSSI errors are valid since wired devices don't have that. So that's ok to ignore.

Regarding the sensors: are there also ones with a _state suffix?
And just for testing, could you set one of your unused digital / frequency inputs (one of channels 15-20) to frequency so we can compare? And one of the digital / analog input (21-26) as well. This way we see if the code evaluates the configured mode correctly.
And are the sensors also unavailable, or do they have meaningful values?

**Comment by danielperna84** [comment]
And while you're at it, could you modify the generic.py HASS is using?
Make this
```python
    def _getNodeData(self, name, metadata, channel=None):
        """ Returns a data point from data"""
        if name in metadata:
            nodeChannelList = metadata[name]
            if len(nodeChannelList) > 1:
                nodeChannel = channel if channel is not None else nodeChannelList[0]
            elif len(nodeChannelList) == 1:
                nodeChannel = nodeChannelList[0]
            if nodeChannel in self.CHANNELS:
                return self._hmchannels[nodeChannel].getValue(name)
```
look like this (added the line with nodeChannel = None)
```python
    def _getNodeData(self, name, metadata, channel=None):
        """ Returns a data point from data"""
        if name in metadata:
            nodeChannelList = metadata[name]
            nodeChannel = None
            if len(nodeChannelList) > 1:
                nodeChannel = channel if channel is not None else nodeChannelList[0]
            elif len(nodeChannelList) == 1:
                nodeChannel = nodeChannelList[0]
            if nodeChannel in self.CHANNELS:
                return self._hmchannels[nodeChannel].getValue(name)
```

This could help us get rid of some of the other exceptions.

**Comment by FREImedia** [comment]
I changed in generic.py.

In HASS on the States page:
sensor.eg_verteiler_iomodul_15_frequency ... sensor.eg_verteiler_iomodul_20_frequency    (states: 15-19=False, 20=0.0)
sensor.eg_verteiler_iomodul_21_value ... sensor.eg_verteiler_iomodul_26_value    (states: 21-25=False, 26= 0.0)
switch.eg_verteiler_iomodul_1 ... switch.eg_verteiler_iomodul_6    (state of all ports is 'unavailable')
Ports 20 and 26 are set to analog.

'homematic.set_dev_value' works.

**Comment by danielperna84** [comment]
So essentially it's just the names of the channels that are incorrect, but the entities themselves work as they should?
Do the states of the digital output entities change if you switch them through the CCU or set_dev_value? Maybe the events sent by the CCU set the correct value. Which doesen't help with switching the switches, but at least we then would know that it's just the call to the CCU that's making problems.

**Comment by FREImedia** [comment]
The switch entities show the correct state, after you turned one of them on.

sensor.eg_verteiler_iomodul_15_frequency:
State: False
```
ID: NEQ0369333
RSSI: false
friendly_name: EG Verteiler IO-Modul 15 FREQUENCY
proxy: wired
unit_of_measurement: Hz
```

The port is set to digital mode - so I guess the additional info like unit of measurement are not correct?

I turned on the wall switch that is connect to port 15, but the state did not change in HASS. On the CCU Webui it was updated.

**Comment by danielperna84** [comment]
Ok, so when starting HASS the values of the sensors are correct, and the issue with those are just cosmetic (incorrect names and units of measurement).
But if you manually (through hardware) change the state of a sensor-channel (flip the switch), the state of the HASS-entity does not update to the new value.

Additionally all digital outputs are correctly created as entities in HASS, but they are not functional and their state also doesn't change to be correct some time later.

Is that where we are right now?

**Comment by FREImedia** [comment]
The first part on the sensors is correct.

The switches switch.eg_verteiler_iomodul_1 ... switch.eg_verteiler_iomodul_6 have the state "unavailable" on HASS startup. Then, after you have changed a switch state manually, (e.g. by the CCU WebUI) all switch states become updated to the correct value. Any further status updates are shown correctly.

**Comment by FREImedia** [comment]
a turn_on service call on switch.eg_verteiler_iomodul_1 works as expected

**Comment by danielperna84** [comment]
Ok.

I've commited some changes to the master branch (stuff that should be working). That will remove the RSSI_DEVICE and handle the nodeList error (now it's just a warning). The changed files are:
- actors.py
- generic.py
- helper.py

This won't improve functionality, but the logoutput should be cleaner without the RSSI-errors. With that working, I would need yet another log output of HASS, including what happens when you flip switches or sensor-entities should update (and fail at that).
And please post as a gist, it's way more comfortable to view in the browser.

**Comment by FREImedia** [comment]
I hope I copied everything you need :-)

https://gist.github.com/FREImedia/645548667e0d4ca743f96bba812e4c1d

**Comment by danielperna84** [comment]
First an attempt to get rid of further errors:
Please change [line 876](https://github.com/home-assistant/home-assistant/blob/dev/homeassistant/components/homematic.py#L876) from
```python
if node in self._data:
```
to
```python
if metadata[node] and node in self._data:
```

And then please a new log where HASS and pyhomematic are set to debug-logging. For that, `configuration.yaml` has to look like that:
```yaml
default: warn
logs:
  homeassistant.components.switch: debug
  homeassistant.components.binary_sensor: debug
  homeassistant.components.sensor: debug
  homeassistant.components.homematic: debug
  homeassistant.core: debug
  pyhomematic: debug
```

**Comment by FREImedia** [comment]
My present for you today ;-)

https://gist.github.com/FREImedia/74db7d2dbc5c527b7c17ecf421de1c90

**Comment by danielperna84** [comment]
This is more of a HASS issue now, and for that @pvizeli is the one who knows the internals best. So Pascal, could you have a look? Gern auch auf Deutsch. ;-)

**Comment by danielperna84** [comment]
Das erste was mich irritiert ist der None Parameter in [Zeile 304](https://gist.github.com/FREImedia/74db7d2dbc5c527b7c17ecf421de1c90#file-hass_log-txt-L304).

**Comment by danielperna84** [comment]
@FREImedia 
Ich habe einen neuen Branch gemacht: [HMWIO_fix_2](https://github.com/danielperna84/pyhomematic/tree/HMWIO_fix_2)
Bitte mal klonen und testen.

In deinem Log stand folgendes:
```
17-01-17 13:50:31 DEBUG (Thread-13) [homeassistant.components.homematic] Handling FREQUENCY: [15, 16, 17, 18, 19, 20]
17-01-17 13:50:31 DEBUG (Thread-13) [homeassistant.components.homematic] Handling VALUE: [21, 22, 23, 24, 25, 26]
17-01-17 13:50:31 DEBUG (Thread-13) [homeassistant.components.homematic] Handling FREQUENCY: [15, 16, 17, 18, 19, 20]
17-01-17 13:50:31 DEBUG (Thread-13) [homeassistant.components.homematic] Handling VALUE: [21, 22, 23, 24, 25, 26]
```
Wie sieht dieser Bereich mit dem neuen Branch aus? Funktionieren vielleicht sogar die sensoren jetzt richtig?

**Comment by FREImedia** [comment]
Jawohl, wir kommen der Sache näher!
Die drei Dateien habe ich kopiert. Die Switches funktionieren nach wie vor, auch das "unavailable" nach dem Startup des HASS konnte ich nicht mehr feststellen.

Die Sensoren funktionieren auch, fast!
Die digitalen Sensoren werden korrekt angezeigt und auch aktualisiert.
Die zwei Analogen (:20 und :26) fehlen jedoch, sind im HASS garnicht erst aufgeführt.

Im Log habe ich dazu nur folgendes gefunden (Debug ist jedoch gerade aus):
`17-01-17 23:37:30 INFO (Thread-13) [pyhomematic.devicetypes.generic] HMGeneric.event: address=NEQXXX01:20, interface_id=homeassistant-wired, key=FREQUENCY, value=0.0`
Reicht dir diese Info?

Aber unterm Strich: Jetzt siehts schon sehr gut aus!

**Comment by danielperna84** [comment]
Es war doch aber so, dass du die Schalter nicht durch HASS schalten konntest. Dieses Problem besteht weiterhin, oder? Also, durch einen Klick auf die Knöpfe im UI. Dass set_dev_value funktioniert ist hierfür erst mal unwichtig, denn das sollte bei allen funktionieren, und wir wollen ja, dass der Schalter im UI funktioniert.

Wegen den fehlenden analogen Sensoren bräuchte ich dann schon noch mal ein Log wo man sehen kann was bei 20 und 26 bei der Initialisierung passiert.

**Comment by FREImedia** [comment]
Die Switches haben gestern auch schon funktioniert, lediglich beim Startup von HASS war der Zustand erst auf "unavailable".
Ich kann die Switches mit dem turn_on/turn_off service und der entity_id (z.B. {"entity_id":"switch.eg_verteiler_iomodul_1"}) schalten. Das funktioniert.

Anbei die Auszüge aus dem Hass Log zum :20 und :26
https://gist.github.com/FREImedia/c0c1ccc6e2458d505f2a0187a5f88a0e

**Comment by danielperna84** [comment]
Ach so, dann hatte ich das missverstanden. Ich dachte, die zeigen nur den richtigen Status an, aber wenn du auf den Schalter klickst schaltet der Aktor nicht.

**Comment by danielperna84** [comment]
Und mir fehlt beim Log der Anfang. Also das, wo das entity in HASS erzeugt wird.

Zusätzlich bitte bei HASS aktualisieren:
- components/sensor/homematic.py durch [das](https://github.com/danielperna84/home-assistant/blob/homematic/homeassistant/components/sensor/homematic.py)

**Comment by FREImedia** [comment]
Aktualisiert und brav den ganzen Anfang kopiert!

https://gist.github.com/FREImedia/885fc236e738968365dc896e99124e86

**Comment by danielperna84** [comment]
Also in pyhomematic werden die Kanäle nun richtig erkannt, was man hieran sieht:
```
17-01-18 00:54:40 DEBUG (Thread-13) [homeassistant.components.homematic] Handling VALUE: [26]
17-01-18 00:54:40 DEBUG (Thread-13) [homeassistant.components.homematic] Handling FREQUENCY: [20]
```
Und wenn ich das richtig lese, dann erzeugt HASS für 20 und 26 binary_sensor entities, und zusätzlich dann noch mal sensor-entities:
```
17-01-18 00:54:40 DEBUG (Thread-13) [homeassistant.components.homematic] homematic.sensor autodiscovery: [
{'channel': 26, 'proxy': 'wired', 'param': 'VALUE', 'platform': 'homematic', 'address': 'NEQXXX01', 'name': 'EG Verteiler IO-Modul VALUE'},
{'channel': 20, 'proxy': 'wired', 'param': 'FREQUENCY', 'platform': 'homematic', 'address': 'NEQXXX01', 'name': 'EG Verteiler IO-Modul FREQUENCY'}]
```
Werde ich mir dann morgen noch mal genauer anschauen.

**Comment by danielperna84** [comment]
Da ich mir leider noch unsicher bin was da passiert bitte mal erneut die homematic.py bearbeiten.
Da drin gibt es die Funktion _get_devices, und da da würde mir eine extra Log-Meldung helfen. So würde ich mir das vorstellen:
```python
def _get_devices(hass, device_type, keys, proxy):
    """Get the Homematic devices."""
    _LOGGER.debug("_get_devices: device_type=%s, keys=%s",
                  device_type, str(keys))
    device_arr = []
```
Aktuell verwirrt mich, dass er mal alle Kanäle nimmt, und mal nur die digitalen:
```
17-01-18 00:54:40 DEBUG (Thread-13) [homeassistant.components.homematic] Handling STATE: [15, 16, 17, 18, 19, 21, 22, 23, 24, 25]
...
17-01-18 00:54:40 DEBUG (Thread-13) [homeassistant.components.homematic] Handling STATE: [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
```
Bei der zweiten Zeile dürften eigentlich nur 20 und 26 in der Liste sein.

**Comment by danielperna84** [comment]
Äh, ich glaub' ich hab's:
```
17-01-18 00:54:41 DEBUG (Thread-1) [homeassistant.components.homematic] Subscribe channel 1 from EG Verteiler IO-Modul 1
17-01-18 00:54:41 DEBUG (Thread-1) [homeassistant.components.homematic] Subscribe channel 26 from EG Verteiler IO-Modul 1
17-01-18 00:54:41 DEBUG (Thread-1) [homeassistant.components.homematic] Subscribe channel 20 from EG Verteiler IO-Modul 1
17-01-18 00:54:41 DEBUG (Thread-1) [homeassistant.components.homematic] EG Verteiler IO-Modul 1 linking done
```
Schau dir mal das EG Verteiler IO-Modul 1 in deiner entity-Liste an. Im Gegensatz zu den anderen switch-entities dürfte das zusätzlich noch VALUE und FREQUENCY als Attribute haben. Hier werden keine eigenen entities erzeugt so wie es aussieht. Stimmt meine Theorie? Wenn ja, was passiert wenn Du testweise noch weitere auf VALUE und FREQUENCY stellst?

**Comment by FREImedia** [comment]
Also, wenn ich im HASS auf der States-Seite bin, gibt es beim "switch.eg_verteiler_iomodul_1" folgendes zu sehen:
State: On
Attributes: 
```
friendly_name: EG Verteiler IO-Modul 1
proxy: wired
ID: NEQXXX01
```
Bei allen anderen Switches sieht das aber genau so aus - hier kann ich keinen Unterschied feststellen.

Ou mist, mir fällt gerade was auf. Die digitalen Eingänge sind alle als binary_sensor aufgeführt.
Analoge Eingänge sind ja keine "binary_sensor"s, sondern normale "sensors", richtig?
Da finde ich sie auch..... (Ich bilde mir zwar ein gestern auf der gesamten Seite nach "_21" mit der Browsersuche gesucht und nichts gefunden zu haben, aber jetzt sind sie da.........)
sensor.eg_verteiler_iomodul_21_value
sensor.eg_verteiler_iomodul_26_value

States: 0.0
Attributes:
```
ID: NEQXXX01
friendly_name: EG Verteiler IO-Modul 26 VALUE
proxy: wired
unit_of_measurement: #
```
Passt das dann so? Ist das so im Sinne des Entwicklers? :-)
Die Funktion kann ich leider nicht prüfen, denn ich habe kein analoges Gerät angeschlossen.

**Comment by FREImedia** [comment]
Lustigerweise sind heute auch nach einem HASS Neustart wieder Error-Meldungen im Log. 

https://gist.github.com/FREImedia/9acb8fe9dafe8362b3d4885005d19626

**Comment by danielperna84** [comment]
Ja, so wäre es tatsächlich richtig. (binary_)sensor-entities entsprechend der Eingangs-Konfiguration, und klickbare Schalter für die digitalen Ausgänge. Für die analogen Ausgänge fehlen passende entities, also fallen die erst mal weg.

Dann wäre das nun also tatsächlich geschafft glaube ich. :)

**Comment by FREImedia** [comment]
Die ERROR-Meldungen tauchen von Port 1 bis 14, soweit ich das Überblicken kann, auf. Diese sind unverändert im Modus digital.

**Comment by danielperna84** [comment]
Passiert das nur beim Start von HASS, oder kommen diese Meldungen auch im laufenden Betrieb?

**Comment by FREImedia** [comment]
Schaut so aus, als würden die nur beim Start kommen. Habe auch nochmal neu gestartet, kamen wieder von :1 - :14

**Comment by danielperna84** [comment]
Dann tippe ich mal darauf, dass der Code von HASS zum initialisieren ein getValue für alle gültigen Parameter macht, unabhängig davon wie der Kanal konfiguriert ist, damit schon beim Start alle entities ihren aktuellen Wert haben. Würde das nicht getan werden wären alle entities erst mal im STATE_UNKNOWN, solange, bis ein Event rein kommen würde um den Status zu aktualisieren.
Ist halt doof, dass das dann auch für Parameter gemacht wird die nicht zutreffend sind. Aber funktional ist das ja keine Einschränkung.

**Comment by FREImedia** [comment]
Ich werde die Tage mal alle "manuellen set_value-Bastel-Schalter" auf die nun erkannten Switches umstellen und testen. Sollte ich nochmal Probleme bekommen, wirst du es erfahren ;-)
Wie lange denkst du denn wird es dauern, bis die Änderungen mit HASS ausgeliefert werden?

Vielen Dank nochmals für deine Hilfe!

**Comment by danielperna84** [comment]
HASS wird immer in einem Intervall von 2 Wochen aktualisiert. Samstags oder Sonntags. Und da das am vergangenen Wochenende der Fall war, dürfte das nächste Update am 29. oder 30. erscheinen.

Ich hatte gehofft es würde noch ein Bugfix Release geben, aber mit 0.36.1 scheint soweit alles zu laufen, und da sich niemand beschwert hat wohl sonst keiner das IO Modul im Einsatz. Ein weiteres Release nur dafür stünde also in keiner Relation. Zumal mit dem neuen pyhomematic auch neue Geräte dazu kommen, was auch nicht so wirklich in ein Bugfix Release rein gehört.

**Comment by danielperna84** [comment]
Die neue pyhomematic version ist nun übrigens fertig, und auch in HASS ist nun alles angepasst. Mit der nächsten Version sollte also alles laufen.
Wenn du keine Mühen scheust und Langeweile hast, könntest Du Dir ein [Development setup](https://home-assistant.io/developers/development_environment/) aufbauen und damit verifizieren, dass auch alles funktionieren wird sobald die Version veröffentlicht wird. Das dann aber lieber auf einer VM oder so machen, denn die dev-version könnte im Vergleich zum aktuellen Release noch unbehandelte Fehler haben.

**Comment by FREImedia** [comment]
Quick exercise, thanks to Docker.

Schaut gut aus, läuft! Das einzige was wie gesagt auffällt, ist die Meldung beim Startup von HASS:
`17-01-22 16:08:23 ERROR (Thread-12) [pyhomematic.devicetypes.generic] HMGeneric.getValue: VALUE on NEQ0369333:14 Exception: <Fault -1: 'Failure'>
`

Ansonsten schaut alles gut aus. Sensors, Binary_Sensors und Switches wurden alle erkannt und scheinen auch zu funktionieren.

**Comment by danielperna84** [comment]
Wie sieht's mit der an diesem Wochenende erschienenen Version aus? Klappt alles out of the box?

**Comment by FREImedia** [comment]
Läuft seit Sonntag, bislang ohne Probleme :-)

**Comment by FREImedia** [comment]
Hui, ich habe ein neues Spielzeug: HMW-IO-12-Sw7-DR
Die Ausgänge werden ohne Probleme erkannt von HASS. Aber leider nicht die Eingänge (auch wenn die nur für Taster vorgesehen sind, trotzdem wäre es praktisch auf die Tasterdrücke in HASS reagieren zu können). Meinst du es ist möglich die Eingänge noch als binary_sensor zu erkennen?

Vielen Dank! :-)

**Comment by danielperna84** [comment]
Eigentlich müssten die Eingänge schon funktionieren. Es gibt hier einen wesentlichen Unterschied zu den Eingängen von Deinem anderen Modul: hier wird mit Events gearbeitet. Schalte mal den Loglevel von HASS auf INFO, und dann betätige mal die Eingänge. Du solltest Event-Meldungen im Log sehen, passend zur Geräte-ID und dem Kanal, sowie ob der Kanal kurz oder lange betätigt wurde (PRESS_SHORT und PRESS_LONG).
In der HomeMatic Doku wird das im Bereich [Devices with buttons](https://home-assistant.io/components/homematic/#devices-with-buttons) beschrieben. Auch wenn es bei Deinem Gerät nicht so wirkt, die Eingänge sind funktionell gesehen keine Sensoren die permanent Status X haben, sondern sie haben eben nur für ein paar ms den PRESS_SHORT oder PRESS_LONG Status, und springen dann quasi wieder direkt zurück auf "aus". Im UI hättest Du dann lauter Sensoren die immer noch den aus-Status zeigen, und das braucht ja keiner. ;-)

**Comment by FREImedia** [comment]
Mit den Events klappt das.
Ich kann in der CCU2 auswählen, ob der Eingang Taster oder Schalter ist - verwundert mich ehrlich gesagt auch etwas, denn ELV bzw EQ-3 schreibt ja, dass dieses Modul nicht zum Auswerten von Schalterzuständen geeignet ist. Was passiert, wenn ich das umstelle, habe ich noch nicht getestet. Wenn ich mal etwas Zeit habe, probiere ich das aus.

**Comment by danielperna84** [comment]
Meine Vermutung wäre, dass der verwendete Parameter dann von `KEY` zu `STATE` wechselt, und man das dann ähnlich wie bei Deinem anderen Modul beim erzeugen des Objektes abfragen muss. In dem Fall könnte man dann tatsächlich binary_sensor entities erzeugen.

**Comment by FREImedia** [comment]
Also, ich habe das mal bei einem Kanal testweise umgestellt - er hat aber nach wie vor weiter mit den Events funktioniert. Ich vermute deshalb mal, dass sich am Protokoll nicht viel geändert hat, liege ich da dann richtig? Was auch immer in der CCU die Umstellung von Taster auf Schalter bewirkt, auch in der CCU-GUI ändert sich an der Anzeige/Bedienung sonst nichts. Bei den Einstellmöglichkeiten für den Eingang kann ich jedoch keine Zeit mehr für den langen Tastendruck mehr einstellen. Eventuell ist das dann auch der Sinn dahinter:
- Taster: Short and Long
- Schalter: Nur eins von beiden
Denn wie eQ-3 schon sagt, zur Zustandsauswertung ist das Teil ja nicht geeignet.. ;-)

**Comment by danielperna84** [comment]
Was da intern passiert weiß ich nicht. Vermutlich macht de CCU intern dann einfach was anderse. Aber da ja mit den Events alles so funktioniert wie es soll gibt's ja eigentlich keinen Änderungsbedarf.
Issue habe ich übrigens geschlossen, weil ich die Tage die letzten fehlenden Geräte (HMW-Sen-SC-12-FM & HMW-Sen-SC-12-DR) implementiert habe. Sollte was davon nicht funktionieren kann dafür ja dann ein neues Issue auf gemacht werden.
Bei Deinem HMW-IO Modul gibt es auch eine kleine Änderung, aber es sollte damit auch noch alles wie vorher funktionieren. In der HASS Version die in 2 Wochen raus kommt sollte das dann drin sein.

**Comment by iuliusmaximilian** [comment]
Hi @danielperna84, mit dem HMW-Sen-SC-12-DR gibt es ein problem, welches ich in https://github.com/thkl/homebridge-homematic/issues/199 beschrieben habe. Kannst du da mal mit rein schauen bitte.

**Comment by danielperna84** [comment]
@iuliusmaximilian 
Hast Du das Problem nur mit homebridge-homematic oder auch mit pyhomematic? Wenn ich mich richtig erinnere habe ich das Gerät nur nach Spezifikation hinzugefügt. Da ich es selbst nicht habe konnte ich nie testen ob es auch wirklich funktioniert. Beklagt hat sich allerdings noch niemand. Insofern weiß ich nicht mit Gewissheit, ob es wirklich funktioniert.

**Comment by iuliusmaximilian** [comment]
@danielperna84 Sowohl im Web UI der CCU2 als auch auf dem iPhone in der PocketControl App. wird der Status richtig aktualisiert, nur im Homebridge > Home App. auf dem gleichen iPhone leider nicht.

**Comment by danielperna84** [comment]
@iuliusmaximilian 
Also pyhomematic hat ja mit Homebridge erst mal nichts zu tun. Das hier ist quasi das Homematic plug-in für Home Assistant. Daher meine Frage, ob es ein Problem ist welches auch pyhomematic betrifft, oder aber nur Homebridge. Wenn das Homebridge plug-in für Homematic ähnlich ist wie pyhomematic, dann muss explizit Support für Geräte implementiert werden. Wenn das für den HMW-Sen-SC-12-DR nicht getan wurde, dann wird es nicht richtig funktionieren. Wenn die Implementierung jedoch da ist aber nicht richtig funktioniert, dann ist da ggf. ein Bug oder ein Konfigurationsproblem.
In beiden Fällen weiß ich nicht, wo das Problem im Homebridge-plugin zu suchen wäre. Wenn es jedoch dasselbe Problem auch mit pyhomematic gibt, dann ist es vermutlich etwas Hardware-spezifisches was bei der Implementierung beachtet werden muss. Würde das Problem in pyhomematic gelöst werden, dann könnte ich vermutlich dazu beitragen das Problem auch für die Homebridge zu lösen.

Insofern nochmal die Frage: funktioniert das Gerät mit Home Assistant (pyhomematic) ordnungsgemäß?
